export {default as i} from "@/public/gallery/0.png"
export {default as ii} from "@/public/gallery/1.png"
export {default as iii} from "@/public/gallery/2.png"
export {default as iv} from "@/public/gallery/3.png"
export {default as v} from "@/public/gallery/4.png"
export {default as vi} from "@/public/gallery/5.png"